/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentClientRouteImport } from './routes/agent-client'
import { Route as AgentSinistreRouteImport } from './routes/agent-sinistre'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IntervenantsRouteImport } from './routes/intervenants'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as SinistresIdRouteImport } from './routes/sinistres.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentClientRoute = AgentClientRouteImport.update({
  id: '/agent-client',
  path: '/agent-client',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSinistreRoute = AgentSinistreRouteImport.update({
  id: '/agent-sinistre',
  path: '/agent-sinistre',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervenantsRoute = IntervenantsRouteImport.update({
  id: '/intervenants',
  path: '/intervenants',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const SinistresIdRoute = SinistresIdRouteImport.update({
  id: '/sinistres/$id',
  path: '/sinistres/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-client': typeof AgentClientRoute
  '/agent-sinistre': typeof AgentSinistreRoute
  '/analytics': typeof AnalyticsRoute
  '/intervenants': typeof IntervenantsRoute
  '/parametres': typeof ParametresRoute
  '/sinistres/$id': typeof SinistresIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-client': typeof AgentClientRoute
  '/agent-sinistre': typeof AgentSinistreRoute
  '/analytics': typeof AnalyticsRoute
  '/intervenants': typeof IntervenantsRoute
  '/parametres': typeof ParametresRoute
  '/sinistres/$id': typeof SinistresIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-client': typeof AgentClientRoute
  '/agent-sinistre': typeof AgentSinistreRoute
  '/analytics': typeof AnalyticsRoute
  '/intervenants': typeof IntervenantsRoute
  '/parametres': typeof ParametresRoute
  '/sinistres/$id': typeof SinistresIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-client'
    | '/agent-sinistre'
    | '/analytics'
    | '/intervenants'
    | '/parametres'
    | '/sinistres/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-client'
    | '/agent-sinistre'
    | '/analytics'
    | '/intervenants'
    | '/parametres'
    | '/sinistres/$id'
  id:
    | '__root__'
    | '/'
    | '/agent-client'
    | '/agent-sinistre'
    | '/analytics'
    | '/intervenants'
    | '/parametres'
    | '/sinistres/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentClientRoute: typeof AgentClientRoute
  AgentSinistreRoute: typeof AgentSinistreRoute
  AnalyticsRoute: typeof AnalyticsRoute
  IntervenantsRoute: typeof IntervenantsRoute
  ParametresRoute: typeof ParametresRoute
  SinistresIdRoute: typeof SinistresIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-client': {
      id: '/agent-client'
      path: '/agent-client'
      fullPath: '/agent-client'
      preLoaderRoute: typeof AgentClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-sinistre': {
      id: '/agent-sinistre'
      path: '/agent-sinistre'
      fullPath: '/agent-sinistre'
      preLoaderRoute: typeof AgentSinistreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervenants': {
      id: '/intervenants'
      path: '/intervenants'
      fullPath: '/intervenants'
      preLoaderRoute: typeof IntervenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinistres/$id': {
      id: '/sinistres/$id'
      path: '/sinistres/$id'
      fullPath: '/sinistres/$id'
      preLoaderRoute: typeof SinistresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentClientRoute: AgentClientRoute,
  AgentSinistreRoute: AgentSinistreRoute,
  AnalyticsRoute: AnalyticsRoute,
  IntervenantsRoute: IntervenantsRoute,
  ParametresRoute: ParametresRoute,
  SinistresIdRoute: SinistresIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
